### ISSUE TITLE
It seems git_curate version 1.1.1 can't work in macos 10.15 with ruby 2.6

### ISSUE THREAD

**Issue by lumm** [matt-harvey/git_curate#14]
It seems git_curate version 1.1.1 can't work in macos 10.15 with ruby 2.6

**Comment by lumm** [comment]
Traceback (most recent call last):
	8: from /usr/local/bin/git-curate:23:in `<main>'
	7: from /usr/local/bin/git-curate:23:in `load'
	6: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.1/exe/git-curate:5:in `<top (required)>'
	5: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.1/lib/git_curate/app.rb:16:in `main'
	4: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.1/lib/git_curate/runner.rb:29:in `run'
	3: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.1/lib/git_curate/branch.rb:70:in `local'
	2: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.1/lib/git_curate/branch.rb:88:in `branch_info'
	1: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.1/lib/git_curate/branch.rb:88:in `map'
/Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.1/lib/git_curate/branch.rb:93:in `block in branch_info': undefined method `upstream' for nil:NilClass (NoMethodError)

**Comment by matt-harvey** [comment]
Hi @lumm,

Thanks for using `git_curate`, and for reporting this issue.

I have not been able to reproduce this unfortunately. Could you please provide some more information? In particular, could you please tell me:
* The output of `git --version`
* The exact output of `git branch`, when run on the repo, branch and commit that you were on when you got the error
* The exact output of `git for-each-ref --format="%(refname:short) .. %(upstream:short) .. %(upstream:track)" refs/heads`, when run on the repo, branch and commit that you were on when you got the error

Feel free to redact (i.e. replace with `xxxxx`) any material that you feel is confidential; but please leave any non-alphanumeric characters (`-`, `/`, `*` etc.) intact.

Thanks again.

**Comment by matt-harvey** [comment]
Hey @lumm, I'm going to close this as I don't have enough information to reproduce the bug. Please feel free to reopen the issue if and when you're able to provide me with further information per above. Thanks.
