### ISSUE TITLE
git curate can't work in macOS 15.7

### ISSUE THREAD

**Issue by lumm** [matt-harvey/git_curate#16]
Hi @matt-harvey , sorry for disturbing you again, I just notice your reply today(I don't login in GitHub very often). git curate still can't work in my computer  macOS 15.7. It could work very well when my macOS version was 13.6, but after I updated my system, the problem got raise. 

Traceback (most recent call last):
	8: from /usr/local/bin/git-curate:23:in `<main>'
	7: from /usr/local/bin/git-curate:23:in `load'
	6: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/exe/git-curate:5:in `<top (required)>'
	5: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/app.rb:16:in `main'
	4: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/runner.rb:29:in `run'
	3: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:70:in `local'
	2: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:88:in `branch_info'
	1: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:88:in `map'
/Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:93:in `block in branch_info': undefined method `upstream' for nil:NilClass (NoMethodError)

My git locate in /usr/local/bin/git
My git version is git version 2.17.0
The output of git for-each-ref --format="%(refname:short) .. %(upstream:short) .. %(upstream:track)" refs/heads is something like below
(omit)
 feature/MAC-2706 ..  .. 
feature/MAC-2868 ..  .. 
feature/MAC-2881 ..  .. 
feature/MAC-2937 ..  .. 
feature/MAC-2943 ..  .. 
(omit)

**Comment by matt-harvey** [comment]
OK thanks @lumm . I'll try to take a look at this in the next week or so.

**Comment by matt-harvey** [comment]
@lumm FYI, I am working on this currently and hope to have a fix released soon.

**Comment by matt-harvey** [comment]
@lumm I wasn't able to reproduce this issue on my own machine, however I've made some changes that I think may fix the issue.

If you wouldn't mind, please install `v1.2.0.beta3` of `git_curate`, as follows:

```
gem install --pre git_curate
```

and let me know if this fixes the issue for you.

(Note the installation process for this version may take a little while, as this version uses the [rugged](https://github.com/libgit2/rugged) library for some operations internally, and that library requires a native C extension to be compiled and installed. This should happen automatically on running `gem install --pre git_curate`, however it may take a few minutes, depending on your machine. FYI, the reason for using `rugged` is to reduce the reliance on parsing `git` command line output internally, which I hope will make `git_curate` behave more consistently between platforms and avoid errors like the one you reported.)

**Comment by lumm** [comment]
Hi @matt-harvey ，I updated to v1.2.0.beta3， the issue was resolved. thank you.

**Comment by matt-harvey** [comment]
Great to hear, @lumm ! Thanks for confirming.

I've released the full `v1.2.0` now, FYI.
